const SUPABASE_URL="",SUPABASE_ANON_KEY="",ET="kome_prerush_entries",OT="kome_prerush_official_videos",ST="kome_prerush_settings",SID="default",LE="kome_prerush_entries_local_v3",LO="kome_prerush_official_v1",LS="kome_prerush_settings_v1",LF="kome_prerush_viewer_favorites_v1";
const PUBLIC_API_BASE="/api/public";
const DEF={event_date:"2026-08-18",official_name:"全てお米の所為です。",official_url:"https://www.youtube.com/@or_should_rice",event_hashtag:"",x_search_url:"",live_playlist_url:"",archive_playlist_url:"",entry_close_minutes:15};
const $=id=>document.getElementById(id),els={form:$("entryForm"),status:$("status"),pending:$("pendingBody"),timeline:$("timeline"),nextTime:$("nextTime"),nextText:$("nextText"),nextMeta1:$("nextMeta1"),nextMeta2:$("nextMeta2"),nextState:$("nextState"),nextKind:$("nextKind"),nextOverlap:$("nextOverlap"),nextWatch:$("nextWatchBtn"),nextNotify:$("nextNotifyBtn"),nextShare:$("nextShareBtn"),dateChip:$("dateChip"),channelLink:$("channelLink"),eventNote:$("eventNote"),approved:$("approvedCount"),official:$("officialCount"),total:$("totalCount"),favoriteCount:$("favoriteCount"),favoritePreview:$("favoritePreview"),plannerStatus:$("plannerStatus"),eventState:$("eventState"),eventStateDetail:$("eventStateDetail"),searchSummary:$("searchSummary"),search:$("scheduleSearch"),laneFilter:$("laneFilter"),timeFilter:$("timeFilter"),jumpUpcoming:$("jumpUpcomingBtn"),clearSearch:$("clearSearchBtn"),copyPage:$("copyPageBtn"),downloadFavorites:$("downloadFavoritesBtn"),downloadAll:$("downloadAllBtn"),clear:$("clearLocal"),eventDateText:$("eventDateText"),heroDate:$("heroDate"),leadDate:$("leadDate"),rulesDateText:$("rulesDateText"),rulesTagText:$("rulesTagText"),hashtagText:$("hashtagText"),hashtagChip:$("hashtagChip"),tagSearch:$("tagSearchLink"),tagPost:$("tagPostLink"),livePlaylist:$("livePlaylistLink"),archivePlaylist:$("archivePlaylistLink"),playlistNote:$("playlistNote"),entryDeadlineText:$("entryDeadlineText"),spacingAdviceText:$("spacingAdviceText"),suggestTimesText:$("suggestTimesText"),promoTemplate:$("promoTemplate"),copyPromo:$("copyPromoBtn"),artist:$("artist"),titleInput:$("title"),parentSlot:$("parentSlot"),startTime:$("startTime"),urlInput:$("url"),noteInput:$("note"),dockJump:$("dockJumpBtn"),dockWatch:$("dockWatchBtn"),dockFavorite:$("dockFavoriteBtn")};
const shared=!!(SUPABASE_URL&&SUPABASE_ANON_KEY&&window.supabase),previewMode=window.location.protocol==="file:",sb=shared?window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
const read=(k,f)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v):f}catch{return f}},write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
let settings={...DEF},schedule=[],approvedEntries=[],filterState="all",searchQuery="",laneFilter="",timeFilter="",currentNextKey="",sourceMode=previewMode?"local":"remote",favorites=new Set(read(LF,[]));
const esc=v=>String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#39;");
const okTime=v=>/^([01]\d|2[0-3]):([0-5]\d)$/.test(String(v||"")),mins=v=>okTime(v)?Number(v.slice(0,2))*60+Number(v.slice(3,5)):1e9,clampInt=(v,min,max,fallback)=>{const n=Math.round(Number(v));return Number.isFinite(n)?Math.min(max,Math.max(min,n)):fallback},uid=()=>window.crypto?.randomUUID?.()||("id-"+Date.now()+"-"+Math.random().toString(16).slice(2));
const safeUrl=(v,empty=false)=>{const s=String(v||"").trim();if(!s)return empty?"":null;try{const u=new URL(s);return ["http:","https:"].includes(u.protocol)?u.toString():null}catch{return null}};
const setStatus=(m,t="")=>{els.status.textContent=m;els.status.className="status "+t};
const normSettings=r=>({event_date:String(r?.event_date||DEF.event_date).trim()||DEF.event_date,official_name:String(r?.official_name||"").trim()||DEF.official_name,official_url:safeUrl(r?.official_url,true)||DEF.official_url,event_hashtag:String(r?.event_hashtag||"").trim(),x_search_url:safeUrl(r?.x_search_url,true)||"",live_playlist_url:safeUrl(r?.live_playlist_url,true)||"",archive_playlist_url:safeUrl(r?.archive_playlist_url,true)||"",entry_close_minutes:clampInt(r?.entry_close_minutes,5,120,DEF.entry_close_minutes)});
const toDate=(d,t)=>!d||!okTime(t)?null:new Date(Number(d.slice(0,4)),Number(d.slice(5,7))-1,Number(d.slice(8,10)),Number(t.slice(0,2)),Number(t.slice(3,5)),0,0);
const fmtDate=d=>{if(!d)return"イベント日 未設定";const x=new Date(d+"T00:00:00");return Number.isNaN(x.getTime())?"イベント日 未設定":new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"long",day:"numeric",weekday:"short"}).format(x)};
const fmtSlashDate=d=>{if(!d)return"----/--/--";const x=new Date(d+"T00:00:00");return Number.isNaN(x.getTime())?"----/--/--":new Intl.DateTimeFormat("ja-JP",{year:"numeric",month:"2-digit",day:"2-digit"}).format(x)};
const fmtShort=d=>!(d instanceof Date)||Number.isNaN(d.getTime())?"日付未設定":new Intl.DateTimeFormat("ja-JP",{month:"numeric",day:"numeric",weekday:"short"}).format(d);
const fmtDiff=ms=>{if(ms<=0)return"まもなく";let s=Math.floor(ms/1000),d=Math.floor(s/86400);s-=d*86400;const h=Math.floor(s/3600);s-=h*3600;const m=Math.floor(s/60);s-=m*60;return[d&&d+"日",(h||d)&&h+"時間",(m||h||d)&&m+"分",s+"秒"].filter(Boolean).join(" ")};
const isSameCalendarDay=(a,b)=>a&&b&&a.getFullYear()===b.getFullYear()&&a.getMonth()===b.getMonth()&&a.getDate()===b.getDate();
const icsText=v=>String(v||"").replaceAll("\\","\\\\").replace(/\r?\n/g,"\\n").replaceAll(",","\\,").replaceAll(";","\\;"),icsStamp=d=>!(d instanceof Date)||Number.isNaN(d.getTime())?"":d.toISOString().replaceAll("-","").replaceAll(":","").replace(/\.\d{3}Z$/,"Z");
const owner=i=>i.kind==="official"?settings.official_name:String(i.artist||"").trim(),itemKey=i=>i.kind+":"+i.id,isFavorite=i=>favorites.has(itemKey(i)),saveFavorites=()=>write(LF,[...favorites]),toggleFavorite=i=>{const key=itemKey(i);if(favorites.has(key))favorites.delete(key);else favorites.add(key);saveFavorites()},setPlannerStatus=m=>{els.plannerStatus.textContent=m};
const badge=s=>s==="approved"?'<span class="badge approved">掲載中</span>':s==="rejected"?'<span class="badge rejected">差し戻し</span>':'<span class="badge pending">審査待ち</span>';
const link=(u,l,cls="linkbtn")=>{const s=safeUrl(u,true);return s?'<a class="'+cls+'" href="'+esc(s)+'" target="_blank" rel="noopener noreferrer">'+esc(l)+"</a>":'<span class="muted">URL準備中</span>'};
const xSearch=(tag,url)=>url||("https://x.com/search?q="+encodeURIComponent(tag)+"&src=typed_query"),xIntent=text=>"https://x.com/intent/post?text="+encodeURIComponent(text);
const setAnchorState=(el,url,label)=>{el.textContent=label;if(url){el.href=url;el.classList.remove("is-disabled")}else{el.href="#";el.classList.add("is-disabled")}},setButtonState=(el,enabled,label)=>{el.textContent=label;el.classList.toggle("is-disabled",!enabled)},flashLabel=(el,msg)=>{const original=el.dataset.label||el.textContent;el.dataset.label=original;el.textContent=msg;setTimeout(()=>{el.textContent=original},1800)};
async function copyText(text){if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true}const area=document.createElement("textarea");area.value=text;area.setAttribute("readonly","");area.style.position="fixed";area.style.opacity="0";document.body.appendChild(area);area.select();const ok=document.execCommand("copy");area.remove();return ok}
async function sharePayload(payload){try{if(navigator.share){await navigator.share(payload);return true}return await copyText(payload.url||payload.text||"")}catch(err){if(err?.name==="AbortError")return false;return false}}
async function api(path,init={}){const res=await fetch(PUBLIC_API_BASE+path,{credentials:"same-origin",...init,headers:{...(init.body?{"Content-Type":"application/json"}:{}),...(init.headers||{})}}),type=res.headers.get("content-type")||"",payload=type.includes("application/json")?await res.json():await res.text();if(!res.ok)throw new Error(typeof payload==="string"?payload:payload?.error||payload?.message||("HTTP "+res.status));return payload}
async function getEntriesDirect(){if(shared){const {data,error}=await sb.from(ET).select("id,artist,title,parent_slot,start_time,url,note,status,created_at").eq("status","approved").order("start_time",{ascending:true});if(error)throw error;return data||[]}return read(LE,[])}
async function getOfficialDirect(){if(shared){const {data,error}=await sb.from(OT).select("id,title,start_time,url,note,created_at").order("start_time",{ascending:true});if(error){console.warn(error);return []}return data||[]}return read(LO,[])}
async function getSettingsDirect(){if(shared){const {data,error}=await sb.from(ST).select("id,event_date,official_name,official_url,event_hashtag,x_search_url,live_playlist_url,archive_playlist_url,entry_close_minutes").eq("id",SID).maybeSingle();if(error){console.warn(error);return normSettings(read(LS,DEF))}return normSettings(data||read(LS,DEF))}return normSettings(read(LS,DEF))}
async function getSnapshot(){if(!previewMode){try{const payload=await api("/data");sourceMode="api";return{entries:payload.entries||[],official:payload.official||[],settings:normSettings(payload.settings||DEF)}}catch(err){if(!shared)throw err}}if(shared){sourceMode="supabase";const [entries,official,rawSettings]=await Promise.all([getEntriesDirect(),getOfficialDirect(),getSettingsDirect()]);return{entries,official,settings:rawSettings}}sourceMode="local";return{entries:read(LE,[]),official:read(LO,[]),settings:normSettings(read(LS,DEF))}}
async function addEntry(v){if(!previewMode){try{await api("/entries",{method:"POST",body:JSON.stringify(v)});sourceMode="api";return}catch(err){if(!shared)throw err}}if(shared){const {error}=await sb.from(ET).insert(v);if(error)throw error;sourceMode="supabase";return}if(!previewMode)throw new Error("参加登録APIに接続できませんでした。");const a=read(LE,[]);a.push(v);write(LE,a);sourceMode="local"}
const merged=(ap,off,st)=>[...ap.map(v=>({kind:"participant",id:v.id,title:String(v.title||"").trim(),artist:String(v.artist||"").trim(),start_time:String(v.start_time||"").trim(),parent_slot:Number(v.parent_slot||0),url:safeUrl(v.url,true),note:String(v.note||"").trim(),date:toDate(st.event_date,v.start_time)})),...off.map(v=>({kind:"official",id:v.id,title:String(v.title||"").trim(),artist:st.official_name,start_time:String(v.start_time||"").trim(),parent_slot:0,url:safeUrl(v.url,true),note:String(v.note||"").trim(),date:toDate(st.event_date,v.start_time)}))].filter(v=>v.title&&okTime(v.start_time)).sort((a,b)=>mins(a.start_time)-mins(b.start_time)||String(a.title).localeCompare(String(b.title),"ja"));
function buildCalendar(list,name){const now=icsStamp(new Date()),rows=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Kome Premiere Rush//JP","CALSCALE:GREGORIAN","METHOD:PUBLISH","X-WR-CALNAME:"+icsText(name)];list.filter(v=>v.date).forEach((v,idx)=>{const start=v.date,end=new Date(start.getTime()+60000),desc=["投稿名義: "+owner(v),"種別: "+(v.kind==="official"?"公式予定":"参加動画"),"開始時刻: "+v.start_time,v.note?"補足: "+v.note:"",v.url?"視聴URL: "+v.url:"","この予定はプレミア開始時刻の目印です。"].filter(Boolean).join("\n");rows.push("BEGIN:VEVENT","UID:"+icsText(itemKey(v)+"-"+idx+"@kome-prerush"),"DTSTAMP:"+now,"DTSTART:"+icsStamp(start),"DTEND:"+icsStamp(end),"SUMMARY:"+icsText(v.title),"DESCRIPTION:"+icsText(desc),v.url?"URL:"+icsText(v.url):"","END:VEVENT")});rows.push("END:VCALENDAR");return rows.filter(Boolean).join("\r\n")}
function downloadCalendar(list,mode){const picks=(mode==="favorites"?list.filter(isFavorite):list).filter(v=>v.date);if(!picks.length){setPlannerStatus(mode==="favorites"?"気になる登録した予定がまだありません。":"保存できる予定がまだありません。");return}const title=mode==="favorites"?"米プレラ 気になる予定":"米プレラ 全予定",fileDate=(settings.event_date||"event").replaceAll("-",""),blob=new Blob([buildCalendar(picks,title)],{type:"text/calendar;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="kome-prerush-"+fileDate+"-"+mode+".ics";document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);setPlannerStatus((mode==="favorites"?"気になる予定":"全予定")+"をカレンダー保存しました。")}
async function sharePage(){const ok=await sharePayload({title:document.title,text:"米プレラのタイムテーブル",url:window.location.href});flashLabel(els.copyPage,ok?"リンクをコピーしました":"共有を閉じました")}
async function shareItemByKey(key,button){const item=schedule.find(v=>itemKey(v)===key);if(!item)return;const ok=await sharePayload({title:item.title,text:owner(item)+" / "+item.start_time+" のプレミア予定",url:item.url||window.location.href});if(button)flashLabel(button,ok?"共有しました":"共有を閉じました")}
function closestUpcoming(list){const now=Date.now();return list.filter(v=>v.date&&v.date.getTime()>=now).sort((a,b)=>a.date-b.date)[0]||null}
function itemPhase(i){if(!i?.date)return{label:"未設定",klass:"past"};const delta=i.date.getTime()-Date.now();if(delta>30*60*1000)return{label:"公開前",klass:"before"};if(delta>0)return{label:"まもなく",klass:"soon"};if(delta>-15*60*1000)return{label:"いま上映中",klass:"live"};return{label:"公開済み",klass:"past"}}
function overlapInfo(item,list){const base=mins(item.start_time),others=list.filter(v=>itemKey(v)!==itemKey(item));return{same:others.filter(v=>mins(v.start_time)===base).length,nearby:others.filter(v=>Math.abs(mins(v.start_time)-base)<=15).length}}
function matchesSearch(i){const q=searchQuery.toLowerCase();if(!q)return true;const hay=[i.title,owner(i),i.note,i.start_time,i.kind==="official"?"公式予定":"参加動画",i.parent_slot?("レーン"+i.parent_slot):""].join(" ").toLowerCase();return hay.includes(q)}
function visibleSchedule(list){return list.filter(v=>{const typeOk=filterState==="all"||filterState===v.kind||(filterState==="favorites"&&isFavorite(v)),laneOk=!laneFilter||(v.kind==="participant"&&String(v.parent_slot)===laneFilter),timeOk=!timeFilter||String(v.start_time||"").startsWith(timeFilter.padStart(2,"0")+":");return typeOk&&laneOk&&timeOk&&matchesSearch(v)})}
function syncFilterButtons(){document.querySelectorAll("[data-filter]").forEach(x=>x.classList.toggle("active",x.dataset.filter===filterState))}
function drawTimeline(list){const shown=visibleSchedule(list),closest=closestUpcoming(shown.length?shown:list);els.timeline.innerHTML=shown.length?shown.map(v=>{const phase=itemPhase(v),overlap=overlapInfo(v,list),overlapText=overlap.same?("同時刻 "+String(overlap.same+1)+"本"):overlap.nearby?("前後15分に "+String(overlap.nearby)+"本"):"被り少なめ";return '<article class="item'+(closest&&closest.id===v.id&&closest.kind===v.kind?' upcoming':'')+'" data-item-key="'+esc(itemKey(v))+'"><div class="timebox"><strong>'+esc(v.start_time)+'</strong><span>'+esc(v.date?fmtShort(v.date):"イベント日未設定")+'</span><span class="small">'+esc(phase.label)+'</span></div><div><div class="tags"><span class="tag '+(v.kind==="official"?"official":"participant")+'">'+(v.kind==="official"?"公式予定":"参加動画")+'</span><span class="tag neutral">'+(v.kind==="official"?"公式":"レーン"+esc(v.parent_slot))+'</span><span class="view-badge '+phase.klass+'">'+esc(phase.label)+'</span><span class="tag neutral">'+esc(overlapText)+'</span></div><h3>'+esc(v.title)+'</h3><p class="owner">'+esc(owner(v))+'</p><p class="desc">'+(esc(v.note)||"補足はまだありません。")+'</p><p class="mini-note">'+(v.url?'動画ページで「通知を受け取る」を押せます。':'URL準備中です。')+'</p></div><div class="item-actions">'+link(v.url,"今見る")+link(v.url,"通知を受け取る","mini-btn")+'<button type="button" class="mini-btn" data-share-item="'+esc(itemKey(v))+'">共有</button><button type="button" class="fav-btn'+(isFavorite(v)?' active':'')+'" data-favorite-toggle="'+esc(itemKey(v))+'">'+(isFavorite(v)?'気になる済み':'気になる')+'</button></div></article>'}).join(""):'<div class="empty">この条件の公開予定はまだありません。</div>';document.querySelectorAll("[data-favorite-toggle]").forEach(btn=>btn.addEventListener("click",e=>{const key=e.currentTarget.dataset.favoriteToggle,hit=schedule.find(v=>itemKey(v)===key);if(!hit)return;toggleFavorite(hit);drawTimeline(schedule);drawFavoritePreview(schedule);drawSearchSummary(schedule)}));document.querySelectorAll("[data-share-item]").forEach(btn=>btn.addEventListener("click",e=>shareItemByKey(e.currentTarget.dataset.shareItem,e.currentTarget)));window.refreshSiteMotion?.(els.timeline)}
function drawPending(list){if(sourceMode!=="local"){els.pending.innerHTML='<tr><td colspan="7" class="empty">共有環境では未掲載の登録を一般公開しません。確認や審査は管理ページで行います。</td></tr>';return}const p=list.filter(v=>v.status!=="approved").sort((a,b)=>Number(a.parent_slot)-Number(b.parent_slot)||mins(a.start_time)-mins(b.start_time));els.pending.innerHTML=p.length?p.map(v=>'<tr><td data-label="状態">'+badge(v.status)+'</td><td class="t" data-label="レーン">レーン'+esc(v.parent_slot)+'</td><td class="t" data-label="時間">'+esc(v.start_time)+'</td><td data-label="タイトル"><span class="song">'+esc(v.title)+'</span></td><td data-label="名義">'+esc(v.artist)+'</td><td data-label="URL">'+(safeUrl(v.url,true)?'<a class="url" href="'+esc(safeUrl(v.url,true))+'" target="_blank" rel="noopener noreferrer">'+esc(safeUrl(v.url,true))+"</a>":'<span class="muted">URLなし</span>')+'</td><td data-label="補足">'+(esc(v.note)||"—")+"</td></tr>").join(""):'<tr><td colspan="7" class="empty">まだ登録はありません。</td></tr>'}
function drawFavoritePreview(list){const picks=list.filter(isFavorite).sort((a,b)=>mins(a.start_time)-mins(b.start_time));els.favoriteCount.textContent=String(picks.length);els.favoritePreview.innerHTML=picks.length?picks.slice(0,4).map(v=>'<div class="plan-item"><strong>'+esc(v.start_time)+' / '+esc(v.title)+'</strong><span class="small">'+esc(owner(v))+"</span></div>").join(""):'<div class="plan-item"><span class="muted">まだ気になる登録はありません。</span></div>';window.refreshSiteMotion?.(els.favoritePreview)}
function drawSearchSummary(list){const shown=visibleSchedule(list),parts=[];if(searchQuery)parts.push('検索「'+searchQuery+'」');if(filterState!=="all")parts.push(filterState==="participant"?"参加動画":filterState==="official"?"公式予定":"気になる");if(laneFilter)parts.push("レーン"+laneFilter);if(timeFilter)parts.push(timeFilter+"時台");els.searchSummary.textContent=(parts.length?parts.join(" / "):"すべて")+" で "+shown.length+" 件表示中"}
function drawEventState(st){const start=toDate(st.event_date,"19:00");if(!start){els.eventState.textContent="未設定";els.eventState.className="state-chip after";els.eventStateDetail.textContent="開催日が未設定です。";return}const end=new Date(start.getTime()+5*60*60*1000),now=Date.now();let label="開催前",klass="before",detail=fmtDate(st.event_date)+" 19:00 開始予定です。";if(now>=start.getTime()&&now<end.getTime()){label="開催中";klass="live";detail="ただいま 19:00〜24:00 の公開時間帯です。タイムテーブルからそのまま視聴準備できます。"}else if(now>=end.getTime()){label="終了";klass="after";detail="この日の公開時間帯は終了しています。見返したい予定は URL や再生リストから確認できます。"}els.eventState.textContent=label;els.eventState.className="state-chip "+klass;els.eventStateDetail.textContent=detail}
function drawCommunity(st){const tag=st.event_hashtag;els.rulesDateText.textContent=fmtDate(st.event_date);if(tag){els.hashtagChip.textContent=tag;els.hashtagText.textContent=tag+" で告知や感想を追えます。";els.rulesTagText.textContent=tag+" を付けて感想や告知を共有できます。";setAnchorState(els.tagSearch,xSearch(tag,st.x_search_url),"Xでタグを見る");setAnchorState(els.tagPost,xIntent(tag+" 米プレラを視聴中"),"感想を投稿")}else{els.hashtagChip.textContent="タグ準備中";els.hashtagText.textContent="感想や告知に使うタグをここに掲載します。";els.rulesTagText.textContent="感想や告知に使うタグは運営設定後にここへ反映されます。";setAnchorState(els.tagSearch,"","Xでタグを見る");setAnchorState(els.tagPost,"","感想を投稿")}setAnchorState(els.livePlaylist,st.live_playlist_url,"今見る用リスト");setAnchorState(els.archivePlaylist,st.archive_playlist_url,"後追い用リスト");els.playlistNote.textContent=st.live_playlist_url||st.archive_playlist_url?"リアタイ用と後追い用の導線をまとめています。":"再生リスト URL が設定されるとここから飛べます。"}
function drawSummary(ap,off,all,st){const label=fmtDate(st.event_date);els.approved.textContent=String(ap.length);els.official.textContent=String(off.length);els.total.textContent=String(all.length);els.dateChip.textContent=label;els.eventDateText.textContent=label;els.heroDate.textContent=fmtSlashDate(st.event_date);els.leadDate.textContent=label;els.eventNote.textContent=label+" のタイムテーブルを表示中です。";if(st.official_url)els.channelLink.href=st.official_url;els.channelLink.textContent=st.official_name+" を見る";drawEventState(st);drawCommunity(st);drawFavoritePreview(all);drawSearchSummary(all)}
function drawNext(){const participantSchedule=schedule.filter(v=>v.kind==="participant");if(!participantSchedule.length){currentNextKey="";els.nextTime.textContent="--";els.nextText.textContent="まだ参加動画はありません。";els.nextMeta1.textContent="参加登録を待っています";els.nextMeta2.textContent="参加動画の次回予定をここに表示します";els.nextKind.textContent="参加動画を待っています";els.nextOverlap.textContent="参加動画の公開時刻が近づくとここに残り時間を表示します。";els.nextState.textContent="公開前";els.nextState.className="view-badge before";setAnchorState(els.nextWatch,"","今すぐ開く");setAnchorState(els.nextNotify,"","通知を受け取る");setButtonState(els.nextShare,false,"この予定を共有");setAnchorState(els.dockWatch,"#timetable","今見る");return}const up=closestUpcoming(participantSchedule);if(!up){currentNextKey="";els.nextTime.textContent="公開済み";els.nextText.textContent="参加動画はすべて公開済みです。";els.nextMeta1.textContent=fmtDate(settings.event_date);els.nextMeta2.textContent="後追い視聴は再生リストや各 URL からどうぞ";els.nextKind.textContent="参加動画は終了";els.nextOverlap.textContent="見逃した作品は後追い用の導線から追えます。";els.nextState.textContent="公開済み";els.nextState.className="view-badge past";setAnchorState(els.nextWatch,settings.archive_playlist_url||"","後追いを開く");setAnchorState(els.nextNotify,"","通知を受け取る");setButtonState(els.nextShare,false,"この予定を共有");setAnchorState(els.dockWatch,settings.archive_playlist_url||"#timetable","今見る");return}currentNextKey=itemKey(up);const phase=itemPhase(up),overlap=overlapInfo(up,schedule);els.nextTime.textContent=fmtDiff(up.date.getTime()-Date.now());els.nextText.textContent=up.title;els.nextMeta1.textContent=owner(up)+" / "+up.start_time+" 開始予定";els.nextMeta2.textContent="参加動画の最短予定";els.nextKind.textContent="参加動画 / レーン"+up.parent_slot;els.nextState.textContent=phase.label;els.nextState.className="view-badge "+phase.klass;els.nextOverlap.textContent=overlap.same?("同時刻に "+String(overlap.same+1)+" 本あります。複数タブで先に開いておくと安心です。"):overlap.nearby?("前後15分に "+String(overlap.nearby)+" 本あります。被りが気になるなら先に通知設定をしておくと追いやすいです。"):"この時間帯は比較的追いやすいです。";setAnchorState(els.nextWatch,up.url,"今すぐ開く");setAnchorState(els.nextNotify,up.url,"通知を受け取る");setButtonState(els.nextShare,!!(up.url||window.location.href),"この予定を共有");setAnchorState(els.dockWatch,up.url||"#timetable","今見る")}
function entryDeadlineInfo(time){const closeMin=settings.entry_close_minutes;if(!settings.event_date||!okTime(time))return{locked:false,text:"登録締切は各枠の "+closeMin+" 分前です。"};const target=toDate(settings.event_date,time);if(!target)return{locked:false,text:"登録締切は各枠の "+closeMin+" 分前です。"};const deadline=new Date(target.getTime()-closeMin*60000),now=new Date();if(now.getTime()>=deadline.getTime())return{locked:true,text:"この開始時刻は開始 "+closeMin+" 分前を過ぎているため登録できません。"};if(isSameCalendarDay(now,target))return{locked:false,text:"この開始時刻の登録締切は "+closeMin+" 分前です。締切まで "+fmtDiff(deadline.getTime()-now.getTime())+"。"};return{locked:false,text:"登録締切は各枠の "+closeMin+" 分前です。"+time+" の枠なら "+closeMin+" 分前が目安です。"}}
function recommendTimes(lane,targetMinute){const sameLane=approvedEntries.filter(v=>Number(v.parent_slot)===Number(lane)),picks=[],seen=new Set();for(let offset=0;offset<=30&&picks.length<3;offset+=1){[targetMinute-offset,targetMinute+offset].forEach(candidate=>{if(candidate<19*60||candidate>23*60+59||seen.has(candidate)||picks.length>=3)return;seen.add(candidate);const ok=sameLane.every(v=>Math.abs(mins(v.start_time)-candidate)>=1);if(ok){const hh=String(Math.floor(candidate/60)).padStart(2,"0"),mm=String(candidate%60).padStart(2,"0");picks.push(hh+":"+mm)}})}return picks}
function updatePromoTemplate(){const artist=String(els.artist.value||"").trim()||"投稿名義",title=String(els.titleInput.value||"").trim()||"作品タイトル",time=String(els.startTime.value||"").trim()||"19:00",url=safeUrl(els.urlInput.value,true)||"",tag=settings.event_hashtag?("\n"+settings.event_hashtag):"",lines=[fmtDate(settings.event_date)+" の米プレラに "+artist+" 名義で参加予定です。",time+" から「"+title+"」をプレミア公開します。",url].filter(Boolean);els.promoTemplate.value=(lines.join("\n")+tag).trim()}
function updateEntryHelper(){const lane=Number(els.parentSlot.value||0),time=String(els.startTime.value||"").trim(),targetMinute=mins(time),deadline=entryDeadlineInfo(time);els.entryDeadlineText.textContent=deadline.text;if(!lane||!okTime(time)){els.spacingAdviceText.textContent="レーンと時刻を選ぶと、前後の枠との距離をここに表示します。";els.suggestTimesText.textContent="おすすめの空き候補をここに表示します。";updatePromoTemplate();return}const sameLane=approvedEntries.filter(v=>Number(v.parent_slot)===lane).sort((a,b)=>mins(a.start_time)-mins(b.start_time)),previous=sameLane.filter(v=>mins(v.start_time)<targetMinute).slice(-1)[0]||null,next=sameLane.find(v=>mins(v.start_time)>targetMinute)||null,exact=sameLane.find(v=>mins(v.start_time)===targetMinute)||null,nearby=schedule.filter(v=>Math.abs(mins(v.start_time)-targetMinute)<=15);if(exact)els.spacingAdviceText.textContent="同じレーン・同じ時刻に掲載中の動画があります。別時刻を選んでください。";else{const prevText=previous?("直前は "+previous.start_time+"（"+Math.abs(targetMinute-mins(previous.start_time))+"分差）"):"直前は空いています",nextText=next?("直後は "+next.start_time+"（"+Math.abs(mins(next.start_time)-targetMinute)+"分差）"):"直後は空いています";els.spacingAdviceText.textContent=prevText+" / "+nextText+"。前後15分には "+nearby.length+" 件あります。"}const picks=recommendTimes(lane,targetMinute);els.suggestTimesText.textContent=picks.length?("近い空き候補: "+picks.join(" / ")):"近い候補は見つかりませんでした。";updatePromoTemplate()}
async function copyPromoTemplate(){const ok=await copyText(els.promoTemplate.value||"");flashLabel(els.copyPromo,ok?"コピーしました":"コピーできませんでした")}
async function render(){const snapshot=await getSnapshot(),entries=snapshot.entries||[],official=snapshot.official||[];settings=normSettings(snapshot.settings||DEF);approvedEntries=entries.filter(v=>v.status==="approved").sort((a,b)=>Number(a.parent_slot)-Number(b.parent_slot)||mins(a.start_time)-mins(b.start_time));const off=official.filter(v=>String(v?.title||"").trim()).sort((a,b)=>mins(a.start_time)-mins(b.start_time));schedule=merged(approvedEntries,off,settings);drawTimeline(schedule);drawPending(entries);drawSummary(approvedEntries,off,schedule,settings);drawNext();updateEntryHelper()}
document.querySelectorAll("[data-filter]").forEach(btn=>btn.addEventListener("click",e=>{filterState=e.currentTarget.dataset.filter;syncFilterButtons();drawTimeline(schedule);drawSearchSummary(schedule)}));
els.search.addEventListener("input",e=>{searchQuery=String(e.currentTarget.value||"").trim();drawTimeline(schedule);drawSearchSummary(schedule)});
els.laneFilter.addEventListener("change",e=>{laneFilter=String(e.currentTarget.value||"").trim();drawTimeline(schedule);drawSearchSummary(schedule)});
els.timeFilter.addEventListener("change",e=>{timeFilter=String(e.currentTarget.value||"").trim();drawTimeline(schedule);drawSearchSummary(schedule)});
els.clearSearch.addEventListener("click",()=>{searchQuery="";laneFilter="";timeFilter="";filterState="all";els.search.value="";els.laneFilter.value="";els.timeFilter.value="";window.syncCustomPickers?.(document);syncFilterButtons();drawTimeline(schedule);drawSearchSummary(schedule)});
els.jumpUpcoming.addEventListener("click",()=>{const target=els.timeline.querySelector(".item.upcoming")||els.timeline.querySelector(".item");if(!target)return;target.scrollIntoView({behavior:"smooth",block:"center"});target.animate?.([{transform:"scale(1)"},{transform:"scale(1.01)"},{transform:"scale(1)"}],{duration:420,easing:"ease-out"})});
els.copyPage.addEventListener("click",sharePage);
els.nextShare.addEventListener("click",()=>{if(currentNextKey&&!els.nextShare.classList.contains("is-disabled"))shareItemByKey(currentNextKey,els.nextShare)});
els.downloadFavorites.addEventListener("click",()=>downloadCalendar(schedule,"favorites"));
els.downloadAll.addEventListener("click",()=>downloadCalendar(schedule,"all"));
els.copyPromo.addEventListener("click",copyPromoTemplate);
[els.artist,els.titleInput,els.parentSlot,els.startTime,els.urlInput,els.noteInput].forEach(el=>el.addEventListener("input",updateEntryHelper));
els.form.addEventListener("submit",async e=>{e.preventDefault();setStatus("");const fd=new FormData(els.form),artist=String(fd.get("artist")||"").trim(),title=String(fd.get("title")||"").trim(),parent=Number(fd.get("parentSlot")||0),time=String(fd.get("startTime")||"").trim(),url=safeUrl(fd.get("url")),note=String(fd.get("note")||"").trim(),deadline=entryDeadlineInfo(time);if(!artist||!title||!parent||!time||!url){setStatus("必須項目を入力してね。","err");return}if(!(parent>=1&&parent<=5)){setStatus("レーンは1～5から選んでね。","err");return}if(!okTime(time)){setStatus("時間の形式が正しくないよ。","err");return}if(deadline.locked){setStatus(deadline.text,"err");return}try{if(approvedEntries.find(v=>Number(v.parent_slot)===parent&&String(v.start_time)===time)){setStatus("そのレーン・時間にはすでに掲載済みの動画があるよ。","err");return}await addEntry({id:uid(),artist,title,parent_slot:parent,start_time:time,url,note,status:"pending",created_at:new Date().toISOString()});els.form.reset();els.parentSlot.value="1";els.startTime.value="19:00";window.syncCustomPickers?.(els.form);setStatus("参加登録を送信したよ。確認が通るとタイムテーブルに載ります。","ok");await render()}catch(err){setStatus("送信に失敗したよ: "+(err.message||err),"err")}});
els.clear.addEventListener("click",async()=>{if(sourceMode!=="local"){setStatus("共有モードではこのボタンは使わないよ。","err");return}if(!confirm("ローカル保存された参加登録を全部消す？"))return;localStorage.removeItem(LE);setStatus("ローカル保存を消したよ。","ok");await render()});
els.dockJump.addEventListener("click",()=>els.jumpUpcoming.click());
els.dockFavorite.addEventListener("click",()=>{filterState="favorites";syncFilterButtons();drawTimeline(schedule);drawSearchSummary(schedule);document.getElementById("timetable").scrollIntoView({behavior:"smooth",block:"start"})});
render().catch(err=>setStatus("読み込みに失敗したよ: "+(err.message||err),"err"));
setInterval(()=>{drawNext();drawEventState(settings)},1000);
